global:
  scrape_timeout: 60s
  scrape_interval: 60s
  evaluation_interval: 60s

  external_labels:
    monitor: 'tumbi-api-monitor'
    
scrape_configs:
  - job_name: "tumbi-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "docker"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["172.17.0.1:9323"]


